# encoding: utf-8
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

source 'https://rubygems.org'

group :development do
  gem 'azure_mgmt_resources', path: 'azure_mgmt_resources'
  gem 'azure_mgmt_storage', path: 'azure_mgmt_storage'
  gem 'azure_mgmt_network', path: 'azure_mgmt_network'
  gem 'azure_mgmt_compute', path: 'azure_mgmt_compute'
end

group :test do
  gem 'rspec'
end