#-------------------------------------------------------------------------
# # Copyright (c) Microsoft and contributors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#--------------------------------------------------------------------------
require 'rspec/core/rake_task'
require 'dotenv/tasks'
require 'open3'

def execute_and_stream(cmd)
  Open3.popen2e(cmd) do |_, stdout_err, wait_thr|
    while line = stdout_err.gets
      puts line
    end

    exit_status = wait_thr.value
    unless exit_status.success?
      abort "FAILED !!! #{cmd}"
    end
  end
end

def each_child
  dirs = Dir.entries('./').select { |f| File.directory?(f) and !(f =='.' || f == '..') }
  dirs.each do |dir|
    Dir.chdir(dir) do
      yield
    end
  end
end

task :spec => :dotenv do
  each_child do
    execute_and_stream('bundle install')
    execute_and_stream('bundle exec rspec')
  end
end

namespace :bundle do
  task :update_children do
    each_child do
      execute_and_stream('bundle update')
    end
  end
end

task :default => :spec
