# encoding: utf-8
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

source 'https://rubygems.org'

group :development, :test do
  gem 'dotenv'
  gem 'os'
  gem 'rake'
  gem 'rspec'
  gem 'vcr'
end

gem 'azure_mgmt_analysis_services',         path: 'management/azure_mgmt_analysis_services'
gem 'azure_mgmt_authorization',             path: 'management/azure_mgmt_authorization'
gem 'azure_mgmt_batch',                     path: 'management/azure_mgmt_batch'
gem 'azure_mgmt_cdn',                       path: 'management/azure_mgmt_cdn'
gem 'azure_mgmt_cognitive_services',        path: 'management/azure_mgmt_cognitive_services'
gem 'azure_mgmt_commerce',                  path: 'management/azure_mgmt_commerce'
gem 'azure_mgmt_compute',                   path: 'management/azure_mgmt_compute'
gem 'azure_mgmt_datalake_analytics',        path: 'management/azure_mgmt_datalake_analytics'
gem 'azure_mgmt_datalake_store',            path: 'management/azure_mgmt_datalake_store'
gem 'azure_mgmt_devtestlabs',               path: 'management/azure_mgmt_devtestlabs'
gem 'azure_mgmt_dns',                       path: 'management/azure_mgmt_dns'
gem 'azure_mgmt_event_hub',                 path: 'management/azure_mgmt_event_hub'
gem 'azure_mgmt_features',                  path: 'management/azure_mgmt_features'
gem 'azure_mgmt_graph',                     path: 'management/azure_mgmt_graph'
gem 'azure_mgmt_monitor',                   path: 'management/azure_mgmt_monitor'
gem 'azure_mgmt_iot_hub',                   path: 'management/azure_mgmt_iot_hub'
gem 'azure_mgmt_key_vault',                 path: 'management/azure_mgmt_key_vault'
gem 'azure_mgmt_locks',                     path: 'management/azure_mgmt_locks'
gem 'azure_mgmt_logic',                     path: 'management/azure_mgmt_logic'
gem 'azure_mgmt_machine_learning',          path: 'management/azure_mgmt_machine_learning'
gem 'azure_mgmt_media_services',            path: 'management/azure_mgmt_media_services'
gem 'azure_mgmt_mobile_engagement',         path: 'management/azure_mgmt_mobile_engagement'
gem 'azure_mgmt_network',                   path: 'management/azure_mgmt_network'
gem 'azure_mgmt_notification_hubs',         path: 'management/azure_mgmt_notification_hubs'
gem 'azure_mgmt_policy',                    path: 'management/azure_mgmt_policy'
gem 'azure_mgmt_powerbi_embedded',          path: 'management/azure_mgmt_powerbi_embedded'
gem 'azure_mgmt_recovery_services',         path: 'management/azure_mgmt_recovery_services'
gem 'azure_mgmt_recovery_services_backup',  path: 'management/azure_mgmt_recovery_services_backup'
gem 'azure_mgmt_redis',                     path: 'management/azure_mgmt_redis'
gem 'azure_mgmt_resources',                 path: 'management/azure_mgmt_resources'
gem 'azure_mgmt_scheduler',                 path: 'management/azure_mgmt_scheduler'
gem 'azure_mgmt_search',                    path: 'management/azure_mgmt_search'
gem 'azure_mgmt_server_management',         path: 'management/azure_mgmt_server_management'
gem 'azure_mgmt_service_bus',               path: 'management/azure_mgmt_service_bus'
gem 'azure_mgmt_sql',                       path: 'management/azure_mgmt_sql'
gem 'azure_mgmt_storage',                   path: 'management/azure_mgmt_storage'
gem 'azure_mgmt_subscriptions',             path: 'management/azure_mgmt_subscriptions'
gem 'azure_mgmt_traffic_manager',           path: 'management/azure_mgmt_traffic_manager'
gem 'azure_mgmt_web',                       path: 'management/azure_mgmt_web'
gem 'azure_sdk',                            path: 'azure_sdk'
