# encoding: utf-8
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

source 'https://rubygems.org'

group :development, :test do
  gem 'dotenv'
  gem 'os'
  gem 'rake'
  gem 'rspec'
  gem 'vcr'
end

gem 'octokit', '~> 4.0'
gem 'azure_mgmt_analysis_services',         path: 'management/azure_mgmt_analysis_services'
gem 'azure_mgmt_api_management',            path: 'management/azure_mgmt_api_management'
gem 'azure_mgmt_authorization',             path: 'management/azure_mgmt_authorization'
gem 'azure_mgmt_automation',                path: 'management/azure_mgmt_automation'
gem 'azure_mgmt_batch',                     path: 'management/azure_mgmt_batch'
gem 'azure_mgmt_billing',                   path: 'management/azure_mgmt_billing'
gem 'azure_mgmt_cdn',                       path: 'management/azure_mgmt_cdn'
gem 'azure_mgmt_cognitive_services',        path: 'management/azure_mgmt_cognitive_services'
gem 'azure_mgmt_commerce',                  path: 'management/azure_mgmt_commerce'
gem 'azure_mgmt_compute',                   path: 'management/azure_mgmt_compute'
gem 'azure_mgmt_consumption',               path: 'management/azure_mgmt_consumption'
gem 'azure_mgmt_container_instance',        path: 'management/azure_mgmt_container_instance'
gem 'azure_mgmt_container_registry',        path: 'management/azure_mgmt_container_registry'
gem 'azure_mgmt_container_service',         path: 'management/azure_mgmt_container_service'
gem 'azure_mgmt_customer_insights',         path: 'management/azure_mgmt_customer_insights'
gem 'azure_mgmt_datalake_analytics',        path: 'management/azure_mgmt_datalake_analytics'
gem 'azure_mgmt_datalake_store',            path: 'management/azure_mgmt_datalake_store'
gem 'azure_mgmt_data_migration',            path: 'management/azure_mgmt_data_migration'
gem 'azure_mgmt_dev_spaces',                path: 'management/azure_mgmt_dev_spaces'
gem 'azure_mgmt_devtestlabs',               path: 'management/azure_mgmt_devtestlabs'
gem 'azure_mgmt_dns',                       path: 'management/azure_mgmt_dns'
gem 'azure_mgmt_event_grid',                path: 'management/azure_mgmt_event_grid'
gem 'azure_mgmt_event_hub',                 path: 'management/azure_mgmt_event_hub'
gem 'azure_mgmt_features',                  path: 'management/azure_mgmt_features'
gem 'azure_mgmt_iot_central',               path: 'management/azure_mgmt_iot_central'
gem 'azure_mgmt_iot_hub',                   path: 'management/azure_mgmt_iot_hub'
gem 'azure_mgmt_key_vault',                 path: 'management/azure_mgmt_key_vault'
gem 'azure_mgmt_kusto',                     path: 'management/azure_mgmt_kusto'
gem 'azure_mgmt_links',                     path: 'management/azure_mgmt_links'
gem 'azure_mgmt_locks',                     path: 'management/azure_mgmt_locks'
gem 'azure_mgmt_logic',                     path: 'management/azure_mgmt_logic'
gem 'azure_mgmt_machine_learning',          path: 'management/azure_mgmt_machine_learning'
gem 'azure_mgmt_managed_applications',      path: 'management/azure_mgmt_managed_applications'
gem 'azure_mgmt_marketplace_ordering',      path: 'management/azure_mgmt_marketplace_ordering'
gem 'azure_mgmt_media_services',            path: 'management/azure_mgmt_media_services'
gem 'azure_mgmt_monitor',                   path: 'management/azure_mgmt_monitor'
gem 'azure_mgmt_msi',                       path: 'management/azure_mgmt_msi'
gem 'azure_mgmt_network',                   path: 'management/azure_mgmt_network'
gem 'azure_mgmt_notification_hubs',         path: 'management/azure_mgmt_notification_hubs'
gem 'azure_mgmt_operational_insights',      path: 'management/azure_mgmt_operational_insights'
gem 'azure_mgmt_policy',                    path: 'management/azure_mgmt_policy'
gem 'azure_mgmt_policy_insights',           path: 'management/azure_mgmt_policy_insights'
gem 'azure_mgmt_powerbi_embedded',          path: 'management/azure_mgmt_powerbi_embedded'
gem 'azure_mgmt_recovery_services',         path: 'management/azure_mgmt_recovery_services'
gem 'azure_mgmt_recovery_services_backup',  path: 'management/azure_mgmt_recovery_services_backup'
gem 'azure_mgmt_recovery_services_site_recovery',  path: 'management/azure_mgmt_recovery_services_site_recovery'
gem 'azure_mgmt_redis',                     path: 'management/azure_mgmt_redis'
gem 'azure_mgmt_relay',                     path: 'management/azure_mgmt_relay'
gem 'azure_mgmt_resources',                 path: 'management/azure_mgmt_resources'
gem 'azure_mgmt_resources_management',      path: 'management/azure_mgmt_resources_management'
gem 'azure_mgmt_scheduler',                 path: 'management/azure_mgmt_scheduler'
gem 'azure_mgmt_search',                    path: 'management/azure_mgmt_search'
gem 'azure_mgmt_security',                  path: 'management/azure_mgmt_security'
gem 'azure_mgmt_service_bus',               path: 'management/azure_mgmt_service_bus'
gem 'azure_mgmt_service_fabric',            path: 'management/azure_mgmt_service_fabric'
gem 'azure_mgmt_signalr',                   path: 'management/azure_mgmt_signalr'
gem 'azure_mgmt_sql',                       path: 'management/azure_mgmt_sql'
gem 'azure_mgmt_sqlvirtualmachine',         path: 'management/azure_mgmt_sqlvirtualmachine'
gem 'azure_mgmt_stor_simple8000_series',    path: 'management/azure_mgmt_stor_simple8000_series'
gem 'azure_mgmt_storage',                   path: 'management/azure_mgmt_storage'
gem 'azure_mgmt_stream_analytics',          path: 'management/azure_mgmt_stream_analytics'
gem 'azure_mgmt_subscriptions',             path: 'management/azure_mgmt_subscriptions'
gem 'azure_mgmt_traffic_manager',           path: 'management/azure_mgmt_traffic_manager'
gem 'azure_mgmt_web',                       path: 'management/azure_mgmt_web'
gem 'azure_graph_rbac',                     path: 'data/azure_graph_rbac'
gem 'azure_cognitiveservices_computervision',   path: 'data/azure_cognitiveservices_computervision'
gem 'azure_cognitiveservices_contentmoderator', path: 'data/azure_cognitiveservices_contentmoderator'
gem 'azure_cognitiveservices_customsearch',     path: 'data/azure_cognitiveservices_customsearch'
gem 'azure_cognitiveservices_entitysearch',     path: 'data/azure_cognitiveservices_entitysearch'
gem 'azure_cognitiveservices_face',             path: 'data/azure_cognitiveservices_face'
gem 'azure_cognitiveservices_imagesearch',      path: 'data/azure_cognitiveservices_imagesearch'
gem 'azure_cognitiveservices_newssearch',       path: 'data/azure_cognitiveservices_newssearch'
gem 'azure_cognitiveservices_spellcheck',       path: 'data/azure_cognitiveservices_spellcheck'
gem 'azure_cognitiveservices_textanalytics',    path: 'data/azure_cognitiveservices_textanalytics'
gem 'azure_cognitiveservices_videosearch',      path: 'data/azure_cognitiveservices_videosearch'
gem 'azure_cognitiveservices_websearch',        path: 'data/azure_cognitiveservices_websearch'
gem 'azure_cognitiveservices_visualsearch',     path: 'data/azure_cognitiveservices_visualsearch'
gem 'azure_event_grid',                         path: 'data/azure_event_grid'
gem 'azure_key_vault',                          path: 'data/azure_key_vault'
gem 'azure_sdk',                            path: 'azure_sdk'
