# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Azure end
module Azure::ARM end
module Azure::ARM::PowerBiEmbedded end
module Azure::ARM::PowerBiEmbedded::Api_2016_01_29 end
