# Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
# Changes may cause incorrect behavior and will be lost if the code is


module Azure::ARM::Compute
  module Models
    #
    # Defines values for CachingTypes
    #
    module CachingTypes
      None = "None"
      ReadOnly = "ReadOnly"
      ReadWrite = "ReadWrite"
    end
  end
end
