# Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
# Changes may cause incorrect behavior and will be lost if the code is


module Azure::ARM::Compute
  #
  # Defines values for OperatingSystemTypes
  #
  module OperatingSystemTypes
    Windows = "Windows"
    Linux = "Linux"
  end
end
