# Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
# Changes may cause incorrect behavior and will be lost if the code is


module Azure::ARM::Compute
  module Models
    #
    # Describes Windows Remote Management configuration of the VM
    #
    class WinRMConfiguration
      # @return [Array<WinRMListener>] Gets or sets the list of Windows Remote
      # Management listeners
      attr_accessor :listeners

      def initialize
        @listeners = [];
      end

      #
      # Validate the object. Throws ArgumentError if validation fails.
      #
      def validate
        @listeners.each{ |e| e.validate if e.respond_to?(:validate) } unless @listeners.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(object)
        object.validate
        output_object = {}

        serialized_property = object.listeners
        if (serialized_property)
          serializedArray = [];
          serialized_property.each do |element|
            if (element)
              element = Azure::ARM::Compute::Models::WinRMListener.serialize_object(element)
            end
            serializedArray.push(element);
          end
          serialized_property = serializedArray;
        end
        output_object['listeners'] = serialized_property unless serialized_property.nil?

        output_object
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [WinRMConfiguration] Deserialized object.
      #
      def self.deserialize_object(object)
        return if object.nil?
        output_object = WinRMConfiguration.new

        deserialized_property = object['listeners']
        if (deserialized_property)
          deserializedArray = [];
          deserialized_property.each do |element1|
            if (element1)
              element1 = Azure::ARM::Compute::Models::WinRMListener.deserialize_object(element1)
            end
            deserializedArray.push(element1);
          end
          deserialized_property = deserializedArray;
        end
        output_object.listeners = deserialized_property

        output_object.validate

        output_object
      end
    end
  end
end
