# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Azure::ARM::Compute
  module Models
    #
    # Defines values for VirtualMachineSizeTypes
    #
    module VirtualMachineSizeTypes
      BasicA0 = "Basic_A0"
      BasicA1 = "Basic_A1"
      BasicA2 = "Basic_A2"
      BasicA3 = "Basic_A3"
      BasicA4 = "Basic_A4"
      StandardA0 = "Standard_A0"
      StandardA1 = "Standard_A1"
      StandardA2 = "Standard_A2"
      StandardA3 = "Standard_A3"
      StandardA4 = "Standard_A4"
      StandardA5 = "Standard_A5"
      StandardA6 = "Standard_A6"
      StandardA7 = "Standard_A7"
      StandardA8 = "Standard_A8"
      StandardA9 = "Standard_A9"
      StandardG1 = "Standard_G1"
      StandardG2 = "Standard_G2"
      StandardG3 = "Standard_G3"
      StandardG4 = "Standard_G4"
      StandardG5 = "Standard_G5"
    end
  end
end
