# Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
# Changes may cause incorrect behavior and will be lost if the code is


module Azure::ARM::Network
  #
  # Defines values for SecurityRuleDirection
  #
  module SecurityRuleDirection
    Inbound = "Inbound"
    Outbound = "Outbound"
  end
end
