# Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
# Changes may cause incorrect behavior and will be lost if the code is


module AzureNetworkManagement
  #
  # Defines values for SecurityRuleAccess
  #
  module SecurityRuleAccess
    Allow = "Allow"
    Deny = "Deny"
  end
end
