# Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
# Changes may cause incorrect behavior and will be lost if the code is


module Azure::ARM::Network
  #
  # Defines values for VirtualNetworkGatewayConnectionType
  #
  module VirtualNetworkGatewayConnectionType
    IPsec = "IPsec"
    Vnet2Vnet = "Vnet2Vnet"
    ExpressRoute = "ExpressRoute"
    VPNClient = "VPNClient"
  end
end
