# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Azure end
module Azure::ARM end
module Azure::ARM::DataLakeStore end
module Azure::ARM::DataLakeStore::Api_2016_11_01 end
module Azure::ARM::DataLakeStore::Api_2015_10_01_preview end
