# encoding: utf-8
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

module Azure end
module Azure::Profiles end
module Azure::Profiles::Latest end
module Azure::Profiles::Latest::Mgmt end
module Azure::Profiles::Latest::AnalysisServices end
module Azure::Profiles::Latest::AnalysisServices::Mgmt end
module Azure::Profiles::Latest::Authorization end
module Azure::Profiles::Latest::Authorization::Mgmt end
module Azure::Profiles::Latest::Automation end
module Azure::Profiles::Latest::Automation::Mgmt end
module Azure::Profiles::Latest::Batch end
module Azure::Profiles::Latest::Batch::Mgmt end
module Azure::Profiles::Latest::Billing end
module Azure::Profiles::Latest::Billing::Mgmt end
module Azure::Profiles::Latest::CDN end
module Azure::Profiles::Latest::CDN::Mgmt end
module Azure::Profiles::Latest::CognitiveServices end
module Azure::Profiles::Latest::CognitiveServices::Mgmt end
module Azure::Profiles::Latest::Commerce end
module Azure::Profiles::Latest::Commerce::Mgmt end
module Azure::Profiles::Latest::Compute end
module Azure::Profiles::Latest::Compute::Mgmt end
module Azure::Profiles::Latest::Consumption end
module Azure::Profiles::Latest::Consumption::Mgmt end
module Azure::Profiles::Latest::ContainerInstance end
module Azure::Profiles::Latest::ContainerInstance::Mgmt end
module Azure::Profiles::Latest::ContainerRegistry end
module Azure::Profiles::Latest::ContainerRegistry::Mgmt end
module Azure::Profiles::Latest::ContainerService end
module Azure::Profiles::Latest::ContainerService::Mgmt end
module Azure::Profiles::Latest::CustomerInsights end
module Azure::Profiles::Latest::CustomerInsights::Mgmt end
module Azure::Profiles::Latest::DataLakeAnalytics end
module Azure::Profiles::Latest::DataLakeAnalytics::Mgmt end
module Azure::Profiles::Latest::DataLakeStore end
module Azure::Profiles::Latest::DataLakeStore::Mgmt end
module Azure::Profiles::Latest::DevTestLabs end
module Azure::Profiles::Latest::DevTestLabs::Mgmt end
module Azure::Profiles::Latest::Dns end
module Azure::Profiles::Latest::Dns::Mgmt end
module Azure::Profiles::Latest::EventGrid end
module Azure::Profiles::Latest::EventGrid::Mgmt end
module Azure::Profiles::Latest::EventHub end
module Azure::Profiles::Latest::EventHub::Mgmt end
module Azure::Profiles::Latest::Features end
module Azure::Profiles::Latest::Features::Mgmt end
module Azure::Profiles::Latest::Graph end
module Azure::Profiles::Latest::Graph::Mgmt end
module Azure::Profiles::Latest::IotHub end
module Azure::Profiles::Latest::IotHub::Mgmt end
module Azure::Profiles::Latest::KeyVault end
module Azure::Profiles::Latest::KeyVault::Mgmt end
module Azure::Profiles::Latest::Links end
module Azure::Profiles::Latest::Links::Mgmt end
module Azure::Profiles::Latest::Locks end
module Azure::Profiles::Latest::Locks::Mgmt end
module Azure::Profiles::Latest::Logic end
module Azure::Profiles::Latest::Logic::Mgmt end
module Azure::Profiles::Latest::MachineLearning end
module Azure::Profiles::Latest::MachineLearning::Mgmt end
module Azure::Profiles::Latest::ManagedApplications end
module Azure::Profiles::Latest::ManagedApplications::Mgmt end
module Azure::Profiles::Latest::MarketplaceOrdering end
module Azure::Profiles::Latest::MarketplaceOrdering::Mgmt end
module Azure::Profiles::Latest::MediaServices end
module Azure::Profiles::Latest::MediaServices::Mgmt end
module Azure::Profiles::Latest::MobileEngagement end
module Azure::Profiles::Latest::MobileEngagement::Mgmt end
module Azure::Profiles::Latest::Monitor end
module Azure::Profiles::Latest::Monitor::Mgmt end
module Azure::Profiles::Latest::ManagedServiceIdentity end
module Azure::Profiles::Latest::ManagedServiceIdentity::Mgmt end
module Azure::Profiles::Latest::Network end
module Azure::Profiles::Latest::Network::Mgmt end
module Azure::Profiles::Latest::NotificationHubs end
module Azure::Profiles::Latest::NotificationHubs::Mgmt end
module Azure::Profiles::Latest::OperationalInsights end
module Azure::Profiles::Latest::OperationalInsights::Mgmt end
module Azure::Profiles::Latest::Policy end
module Azure::Profiles::Latest::Policy::Mgmt end
module Azure::Profiles::Latest::PowerBiEmbedded end
module Azure::Profiles::Latest::PowerBiEmbedded::Mgmt end
module Azure::Profiles::Latest::RecoveryServices end
module Azure::Profiles::Latest::RecoveryServices::Mgmt end
module Azure::Profiles::Latest::RecoveryServicesBackup end
module Azure::Profiles::Latest::RecoveryServicesBackup::Mgmt end
module Azure::Profiles::Latest::RecoveryServicesSiteRecovery end
module Azure::Profiles::Latest::RecoveryServicesSiteRecovery::Mgmt end
module Azure::Profiles::Latest::Redis end
module Azure::Profiles::Latest::Redis::Mgmt end
module Azure::Profiles::Latest::Relay end
module Azure::Profiles::Latest::Relay::Mgmt end
module Azure::Profiles::Latest::Resources end
module Azure::Profiles::Latest::Resources::Mgmt end
module Azure::Profiles::Latest::ResourcesManagement end
module Azure::Profiles::Latest::ResourcesManagement::Mgmt end
module Azure::Profiles::Latest::Scheduler end
module Azure::Profiles::Latest::Scheduler::Mgmt end
module Azure::Profiles::Latest::Search end
module Azure::Profiles::Latest::Search::Mgmt end
module Azure::Profiles::Latest::ServerManagement end
module Azure::Profiles::Latest::ServerManagement::Mgmt end
module Azure::Profiles::Latest::ServiceBus end
module Azure::Profiles::Latest::ServiceBus::Mgmt end
module Azure::Profiles::Latest::ServiceFabric end
module Azure::Profiles::Latest::ServiceFabric::Mgmt end
module Azure::Profiles::Latest::SQL end
module Azure::Profiles::Latest::SQL::Mgmt end
module Azure::Profiles::Latest::StorSimple8000Series end
module Azure::Profiles::Latest::StorSimple8000Series::Mgmt end
module Azure::Profiles::Latest::Storage end
module Azure::Profiles::Latest::Storage::Mgmt end
module Azure::Profiles::Latest::StreamAnalytics end
module Azure::Profiles::Latest::StreamAnalytics::Mgmt end
module Azure::Profiles::Latest::Subscriptions end
module Azure::Profiles::Latest::Subscriptions::Mgmt end
module Azure::Profiles::Latest::TrafficManager end
module Azure::Profiles::Latest::TrafficManager::Mgmt end
module Azure::Profiles::Latest::Web end
module Azure::Profiles::Latest::Web::Mgmt end
