---
http_interactions:
- request:
    method: get
    uri: https://login.windows.net/<AZURE_TENANT_ID>/oauth2/token
    body:
      encoding: UTF-8
      string: resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=<AZURE_CLIENT_ID>&client_secret=<AZURE_CLIENT_SECRET>&grant_type=client_credentials
    headers:
      User-Agent:
      - Faraday v0.9.2
      content-type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      server:
      - Microsoft-IIS/8.5
      x-ms-request-id:
      - 5391d32b-d419-4c16-b6d1-734ed74e5dab
      client-request-id:
      - d8ae6387-cc8e-42ab-b556-42ed7e94bc13
      x-ms-gateway-service-instanceid:
      - ESTSFE_IN_165
      x-content-type-options:
      - nosniff
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      p3p:
      - CP="DSP CUR OTPi IND OTRi ONL FIN"
      set-cookie:
      - flight-uxoptin=true; path=/; secure; HttpOnly, esctx=AAABAAAAiL9Kn2Z27UubvWFPbm0gLVB5mqxk4Ow5WrCzM2rquZh_5xE_xx4yanGBtCASvW3qO3zwDAE8NGJ6xkspxmB1sxqJ7YrRgIC2Xy7SkE0rW6MquzBSyaDCuUzuZPu9YNKmG3LRbOLvS2Pxa8Mzh4JtN74Jw3ip3fLAKRETec_BmYgvG98uuWknJM1Bd-nEWCU7IAA;
        domain=.login.windows.net; path=/; secure; HttpOnly, x-ms-gateway-slice=productiona;
        path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
      x-powered-by:
      - ASP.NET
      date:
      - Thu, 19 May 2016 03:20:26 GMT
      connection:
      - close
      content-length:
      - '1234'
    body:
      encoding: UTF-8
      string: '{"token_type":"Bearer","expires_in":"3599","expires_on":"1463631626","not_before":"1463627726","resource":"https://management.core.windows.net/","access_token":"<ACCESS_TOKEN>"}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:20:28 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2016-02-01
    body:
      encoding: UTF-8
      string: '{"location":"westus"}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 0221e436-e56d-4e98-8671-b3bb6a402813
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-length:
      - '217'
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-writes:
      - '1193'
      x-ms-request-id:
      - fc8ab858-f670-4c01-a7fc-e89fa8c93683
      x-ms-correlation-request-id:
      - fc8ab858-f670-4c01-a7fc-e89fa8c93683
      x-ms-routing-request-id:
      - WESTUS:20160519T032026Z:fc8ab858-f670-4c01-a7fc-e89fa8c93683
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:20:26 GMT
      connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources","name":"RubySDKTest_azure_mgmt_resources","location":"westus","properties":{"provisioningState":"Succeeded"}}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:20:29 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/%7E%60123/providers/Microsoft.Resources/deployments/bar?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - a503b232-6f56-4b72-a4cd-da3e6c07b75c
      accept-language:
      - en-US
  response:
    status:
      code: 400
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      x-ms-failure-cause:
      - gateway
      x-ms-ratelimit-remaining-subscription-reads:
      - '14915'
      x-ms-request-id:
      - 47ae8b31-5dd5-426a-b79f-b91b84e2da8b
      x-ms-correlation-request-id:
      - 47ae8b31-5dd5-426a-b79f-b91b84e2da8b
      x-ms-routing-request-id:
      - WESTUS:20160519T032027Z:47ae8b31-5dd5-426a-b79f-b91b84e2da8b
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:20:26 GMT
      connection:
      - close
      content-length:
      - '195'
    body:
      encoding: UTF-8
      string: '{"error":{"code":"InvalidResourceGroup","message":"The provided resource
        group name ''~`123'' has these invalid characters: ''~`''. The name can only
        be a letter, digit, ''-'', ''.'', ''('', '')'' or ''_''."}}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:20:29 GMT
- request:
    method: delete
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - f400be03-1cb1-477f-b50f-4254ba1c61a7
      accept-language:
      - en-US
  response:
    status:
      code: 202
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      location:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2016-02-01
      retry-after: '1'
      x-ms-ratelimit-remaining-subscription-writes:
      - '1195'
      x-ms-request-id:
      - 965235f8-e6b5-4c5e-a952-ef9810b32bf5
      x-ms-correlation-request-id:
      - 965235f8-e6b5-4c5e-a952-ef9810b32bf5
      x-ms-routing-request-id:
      - WESTUS:20160519T032027Z:965235f8-e6b5-4c5e-a952-ef9810b32bf5
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:20:26 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 19 May 2016 03:20:29 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 03a63706-5884-4dbe-b287-0ad1e6bb17b5
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-reads:
      - '14983'
      x-ms-request-id:
      - fd4b9b85-0250-458e-bd2d-14a07964684c
      x-ms-correlation-request-id:
      - fd4b9b85-0250-458e-bd2d-14a07964684c
      x-ms-routing-request-id:
      - WESTUS:20160519T032128Z:fd4b9b85-0250-458e-bd2d-14a07964684c
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:21:27 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 19 May 2016 03:21:30 GMT
recorded_with: VCR 3.0.1
