---
http_interactions:
- request:
    method: get
    uri: https://login.windows.net/<AZURE_TENANT_ID>/oauth2/token
    body:
      encoding: UTF-8
      string: resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=<AZURE_CLIENT_ID>&client_secret=<AZURE_CLIENT_SECRET>&grant_type=client_credentials
    headers:
      User-Agent:
      - Faraday v0.9.2
      content-type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      server:
      - Microsoft-IIS/8.5
      x-ms-request-id:
      - afa3ea18-7d73-4612-9324-91207f9de490
      client-request-id:
      - dae7299b-f9c7-4cf0-bca0-fe15249722a6
      x-ms-gateway-service-instanceid:
      - ESTSFE_IN_399
      x-content-type-options:
      - nosniff
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      p3p:
      - CP="DSP CUR OTPi IND OTRi ONL FIN"
      set-cookie:
      - flight-uxoptin=true; path=/; secure; HttpOnly, esctx=AAABAAAAiL9Kn2Z27UubvWFPbm0gLf9skqkCkN0HdvwU9dhDYmTJi6rUDENrX3T4ARIP4cryZqWbtZuDJb1O88wJMww5R9PciAWD24ZrmIRVaNxdVCSzqgUf4AB4IxKypvDWiaZY3rdoQZrJNx4kJFvbCfiKCRC-f67eSvbPKoQBt4z4FcPBeXZqCBML21rzBPvMRamZIAA;
        domain=.login.windows.net; path=/; secure; HttpOnly, x-ms-gateway-slice=productiona;
        path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
      x-powered-by:
      - ASP.NET
      date:
      - Thu, 19 May 2016 03:25:55 GMT
      connection:
      - close
      content-length:
      - '1234'
    body:
      encoding: UTF-8
      string: '{"token_type":"Bearer","expires_in":"3599","expires_on":"1463631955","not_before":"1463628055","resource":"https://management.core.windows.net/","access_token":"<ACCESS_TOKEN>"}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:25:58 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2016-02-01
    body:
      encoding: UTF-8
      string: '{"location":"westus"}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 8f7c4cdf-d999-4b73-9b19-c962214bdb5c
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-length:
      - '217'
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-writes:
      - '1196'
      x-ms-request-id:
      - 6d2f78f9-7a2e-405e-80f6-dcbc74bdb737
      x-ms-correlation-request-id:
      - 6d2f78f9-7a2e-405e-80f6-dcbc74bdb737
      x-ms-routing-request-id:
      - WESTUS:20160519T032556Z:6d2f78f9-7a2e-405e-80f6-dcbc74bdb737
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:25:55 GMT
      connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources","name":"RubySDKTest_azure_mgmt_resources","location":"westus","properties":{"provisioningState":"Succeeded"}}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:25:59 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - d0104674-34a2-47a2-aaa7-2ecd8d3a8a55
      accept-language:
      - en-US
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14962'
      x-ms-request-id:
      - 1baf1b15-17e4-4620-9c5a-86369cd77ee2
      x-ms-correlation-request-id:
      - 1baf1b15-17e4-4620-9c5a-86369cd77ee2
      x-ms-routing-request-id:
      - WESTUS:20160519T032557Z:1baf1b15-17e4-4620-9c5a-86369cd77ee2
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:25:56 GMT
      connection:
      - close
      content-length:
      - '133'
    body:
      encoding: ASCII-8BIT
      string: '{"value":[]}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:25:59 GMT
- request:
    method: delete
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 9ce8d941-6a5b-4a09-8aba-730bcbf8c165
      accept-language:
      - en-US
  response:
    status:
      code: 202
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      location:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2016-02-01
      retry-after: '1'
      x-ms-ratelimit-remaining-subscription-writes:
      - '1192'
      x-ms-request-id:
      - 06b99bfa-0b79-4e34-8e06-90104c581728
      x-ms-correlation-request-id:
      - 06b99bfa-0b79-4e34-8e06-90104c581728
      x-ms-routing-request-id:
      - WESTUS:20160519T032557Z:06b99bfa-0b79-4e34-8e06-90104c581728
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:25:56 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 19 May 2016 03:25:59 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 0afd68f0-d65d-415c-8b83-bcfbcf203ecb
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-reads:
      - '14982'
      x-ms-request-id:
      - 8af5c35a-c88e-4423-83e9-5e7a8eeeed58
      x-ms-correlation-request-id:
      - 8af5c35a-c88e-4423-83e9-5e7a8eeeed58
      x-ms-routing-request-id:
      - WESTUS:20160519T032657Z:8af5c35a-c88e-4423-83e9-5e7a8eeeed58
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:26:57 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 19 May 2016 03:27:00 GMT
recorded_with: VCR 3.0.1
