---
http_interactions:
- request:
    method: get
    uri: https://login.windows.net/<AZURE_TENANT_ID>/oauth2/token
    body:
      encoding: UTF-8
      string: resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=<AZURE_CLIENT_ID>&client_secret=<AZURE_CLIENT_SECRET>&grant_type=client_credentials
    headers:
      User-Agent:
      - Faraday v0.9.2
      content-type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      server:
      - Microsoft-IIS/8.5
      x-ms-request-id:
      - aa34fc2e-56b9-4956-a737-ecc931f5e79f
      client-request-id:
      - 2119fe0f-e684-46ab-a32a-e86c1d9e54a6
      x-ms-gateway-service-instanceid:
      - ESTSFE_IN_72
      x-content-type-options:
      - nosniff
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      p3p:
      - CP="DSP CUR OTPi IND OTRi ONL FIN"
      set-cookie:
      - flight-uxoptin=true; path=/; secure; HttpOnly, esctx=AAABAAAAiL9Kn2Z27UubvWFPbm0gLa6ezAjNpVfyoY1WO1m4zaUX4XFOw7cfdpO909eILXN3zH-UAN5Gh03xvgJxWFwKFR-ntiqs9GFqURkUeKJB1vPNSysUbGyfGpw9ZTcg0I08HYKoqexcy-f5fOoAtqbQXCOfFaoXUmenoKcz935ijd6-X_ddAN-wK_I93TAQlewKIAA;
        domain=.login.windows.net; path=/; secure; HttpOnly, x-ms-gateway-slice=productiona;
        path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
      x-powered-by:
      - ASP.NET
      date:
      - Thu, 19 May 2016 03:11:37 GMT
      connection:
      - close
      content-length:
      - '1234'
    body:
      encoding: UTF-8
      string: '{"token_type":"Bearer","expires_in":"3599","expires_on":"1463631097","not_before":"1463627197","resource":"https://management.core.windows.net/","access_token":"<ACCESS_TOKEN>"}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:11:40 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2016-02-01
    body:
      encoding: UTF-8
      string: '{"location":"westus"}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - fed9e53f-118e-48b8-89e7-a466a091ba67
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-length:
      - '217'
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-writes:
      - '1196'
      x-ms-request-id:
      - e123a383-c006-44a0-ba0c-3c4bd15144f2
      x-ms-correlation-request-id:
      - e123a383-c006-44a0-ba0c-3c4bd15144f2
      x-ms-routing-request-id:
      - WESTUS:20160519T031138Z:e123a383-c006-44a0-ba0c-3c4bd15144f2
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:11:37 GMT
      connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources","name":"RubySDKTest_azure_mgmt_resources","location":"westus","properties":{"provisioningState":"Succeeded"}}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:11:40 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test?api-version=2016-02-01
    body:
      encoding: UTF-8
      string: '{"properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json"},"parameters":{"databaseAccountName":{"value":"mydocs-test"}},"mode":"Incremental"}}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 9a1ef41c-94ff-47a2-be18-4d4f6b3fe88c
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      azure-asyncoperation:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test/operationStatuses/08587379793861394411?api-version=2016-02-01
      x-ms-ratelimit-remaining-subscription-writes:
      - '1195'
      x-ms-request-id:
      - 0e135c96-1f84-4e39-82b8-9090ceda4006
      x-ms-correlation-request-id:
      - 0e135c96-1f84-4e39-82b8-9090ceda4006
      x-ms-routing-request-id:
      - WESTUS:20160519T031139Z:0e135c96-1f84-4e39-82b8-9090ceda4006
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:11:39 GMT
      connection:
      - close
      content-length:
      - '778'
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test","name":"Deployment_test","properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json","contentVersion":"1.0.0.0"},"parameters":{"databaseAccountName":{"type":"String","value":"mydocs-test"}},"mode":"Incremental","provisioningState":"Accepted","timestamp":"2016-05-19T03:11:39.7515429Z","duration":"PT0.4133147S","correlationId":"0e135c96-1f84-4e39-82b8-9090ceda4006","providers":[{"namespace":"Microsoft.DocumentDB","resourceTypes":[{"resourceType":"databaseAccounts","locations":["westus"]}]}],"dependencies":[]}}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:11:42 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test/operationStatuses/08587379793861394411?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 21f0049d-03b7-413f-889c-fbc87fc6da24
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14982'
      x-ms-request-id:
      - 7e2c5a66-24d7-4d46-9960-3210d9b413ca
      x-ms-correlation-request-id:
      - 7e2c5a66-24d7-4d46-9960-3210d9b413ca
      x-ms-routing-request-id:
      - WESTUS:20160519T031210Z:7e2c5a66-24d7-4d46-9960-3210d9b413ca
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:12:09 GMT
      connection:
      - close
      content-length:
      - '140'
    body:
      encoding: ASCII-8BIT
      string: '{"status":"Running"}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:12:12 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test/operationStatuses/08587379793861394411?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - acb7c15b-a732-427c-917d-13e3c5311216
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14990'
      x-ms-request-id:
      - 543c0b9d-709f-4e71-ab0d-160926911dc7
      x-ms-correlation-request-id:
      - 543c0b9d-709f-4e71-ab0d-160926911dc7
      x-ms-routing-request-id:
      - WESTUS:20160519T031240Z:543c0b9d-709f-4e71-ab0d-160926911dc7
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:12:39 GMT
      connection:
      - close
      content-length:
      - '141'
    body:
      encoding: ASCII-8BIT
      string: '{"status":"Succeeded"}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:12:42 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 5d403b94-1afc-4b97-91e4-44c3fa07b13d
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14971'
      x-ms-request-id:
      - 0d639685-6b4f-4467-a3e5-a90d9ff815d8
      x-ms-correlation-request-id:
      - 0d639685-6b4f-4467-a3e5-a90d9ff815d8
      x-ms-routing-request-id:
      - WESTUS:20160519T031240Z:0d639685-6b4f-4467-a3e5-a90d9ff815d8
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:12:39 GMT
      connection:
      - close
      content-length:
      - '683'
    body:
      encoding: ASCII-8BIT
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test","name":"Deployment_test","properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json","contentVersion":"1.0.0.0"},"parameters":{"databaseAccountName":{"type":"String","value":"mydocs-test"}},"mode":"Incremental","provisioningState":"Succeeded","timestamp":"2016-05-19T03:12:39.5487618Z","duration":"PT1M0.2105336S","correlationId":"0e135c96-1f84-4e39-82b8-9090ceda4006","providers":[{"namespace":"Microsoft.DocumentDB","resourceTypes":[{"resourceType":"databaseAccounts","locations":["westus"]}]}],"dependencies":[],"outputResources":[{"id":"Microsoft.DocumentDB/databaseAccounts/mydocs-test"}]}}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:12:42 GMT
- request:
    method: delete
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - c1f27fa3-7de4-4282-b2ec-f94bdfde1210
      accept-language:
      - en-US
  response:
    status:
      code: 202
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      location:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2016-02-01
      retry-after: '1'
      x-ms-ratelimit-remaining-subscription-writes:
      - '1196'
      x-ms-request-id:
      - a5a2b26a-c56c-4efb-b6d7-afe2991e41de
      x-ms-correlation-request-id:
      - a5a2b26a-c56c-4efb-b6d7-afe2991e41de
      x-ms-routing-request-id:
      - WESTUS:20160519T031241Z:a5a2b26a-c56c-4efb-b6d7-afe2991e41de
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:12:40 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 19 May 2016 03:12:43 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - ed9100f1-5805-4a58-bc63-401d032d11be
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-reads:
      - '14949'
      x-ms-request-id:
      - b79c8dbe-bb9d-4227-a644-62a32c353e9e
      x-ms-correlation-request-id:
      - b79c8dbe-bb9d-4227-a644-62a32c353e9e
      x-ms-routing-request-id:
      - WESTUS:20160519T031412Z:b79c8dbe-bb9d-4227-a644-62a32c353e9e
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:14:11 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 19 May 2016 03:14:14 GMT
recorded_with: VCR 3.0.1
