---
http_interactions:
- request:
    method: get
    uri: https://login.windows.net/<AZURE_TENANT_ID>/oauth2/token
    body:
      encoding: UTF-8
      string: resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=<AZURE_CLIENT_ID>&client_secret=<AZURE_CLIENT_SECRET>&grant_type=client_credentials
    headers:
      User-Agent:
      - Faraday v0.9.2
      content-type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      server:
      - Microsoft-IIS/8.5
      x-ms-request-id:
      - 77f2c9b9-08e1-458e-b137-ad93ff60d486
      client-request-id:
      - 3d1c91b4-5dbf-4a22-9c69-3d97325d15a0
      x-ms-gateway-service-instanceid:
      - ESTSFE_IN_142
      x-content-type-options:
      - nosniff
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      p3p:
      - CP="DSP CUR OTPi IND OTRi ONL FIN"
      set-cookie:
      - flight-uxoptin=true; path=/; secure; HttpOnly, esctx=AAABAAAAiL9Kn2Z27UubvWFPbm0gLZqkGiBoUzAXoU50Bzda3uR4TUeUj3Taqmhrc82Gb1IR03xsQlr3W98gSfiKYaEIi-C_uIQ-8iDmPDMRodlytXO8KsOE3g5zK7PzuZYpFLXZzkptz7TYBpzP4KQhNJRgxh7TZmHdH1gk_orz-bXSBLWew3t1t0kld0IWX2NFm5oNIAA;
        domain=.login.windows.net; path=/; secure; HttpOnly, x-ms-gateway-slice=productiona;
        path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
      x-powered-by:
      - ASP.NET
      date:
      - Thu, 19 May 2016 03:15:15 GMT
      connection:
      - close
      content-length:
      - '1234'
    body:
      encoding: UTF-8
      string: '{"token_type":"Bearer","expires_in":"3600","expires_on":"1463631315","not_before":"1463627415","resource":"https://management.core.windows.net/","access_token":"<ACCESS_TOKEN>"}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:15:18 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2016-02-01
    body:
      encoding: UTF-8
      string: '{"location":"westus"}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 3b0164ba-3b11-42b8-ac74-b985c3e378b8
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-length:
      - '217'
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-writes:
      - '1194'
      x-ms-request-id:
      - 08c343e6-6218-4c68-bf4e-ff1ba87d0779
      x-ms-correlation-request-id:
      - 08c343e6-6218-4c68-bf4e-ff1ba87d0779
      x-ms-routing-request-id:
      - WESTUS:20160519T031516Z:08c343e6-6218-4c68-bf4e-ff1ba87d0779
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:15:16 GMT
      connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources","name":"RubySDKTest_azure_mgmt_resources","location":"westus","properties":{"provisioningState":"Succeeded"}}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:15:18 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test?api-version=2016-02-01
    body:
      encoding: UTF-8
      string: '{"properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json"},"parameters":{"databaseAccountName":{"value":"mydocs-test"}},"mode":"Incremental"}}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 7c994c05-6e2d-4f2f-b2f1-4360fdbef402
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      azure-asyncoperation:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test/operationStatuses/08587379791680341059?api-version=2016-02-01
      x-ms-ratelimit-remaining-subscription-writes:
      - '1194'
      x-ms-request-id:
      - 983aa8ef-b859-498b-b380-15235201427c
      x-ms-correlation-request-id:
      - 983aa8ef-b859-498b-b380-15235201427c
      x-ms-routing-request-id:
      - WESTUS:20160519T031517Z:983aa8ef-b859-498b-b380-15235201427c
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:15:16 GMT
      connection:
      - close
      content-length:
      - '778'
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test","name":"Deployment_test","properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json","contentVersion":"1.0.0.0"},"parameters":{"databaseAccountName":{"type":"String","value":"mydocs-test"}},"mode":"Incremental","provisioningState":"Accepted","timestamp":"2016-05-19T03:15:17.7041656Z","duration":"PT0.2606185S","correlationId":"983aa8ef-b859-498b-b380-15235201427c","providers":[{"namespace":"Microsoft.DocumentDB","resourceTypes":[{"resourceType":"databaseAccounts","locations":["westus"]}]}],"dependencies":[]}}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:15:20 GMT
- request:
    method: post
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test/cancel?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 2df43150-310d-4c8d-967e-a9aa8058a77e
      accept-language:
      - en-US
  response:
    status:
      code: 204
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-writes:
      - '1198'
      x-ms-request-id:
      - b76c5ccb-09e5-49d9-abf2-30184ea21205
      x-ms-correlation-request-id:
      - b76c5ccb-09e5-49d9-abf2-30184ea21205
      x-ms-routing-request-id:
      - WESTUS:20160519T031518Z:b76c5ccb-09e5-49d9-abf2-30184ea21205
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:15:17 GMT
      connection:
      - close
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 19 May 2016 03:15:20 GMT
- request:
    method: delete
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 8b1f5d2f-adae-402f-afa8-df8e1bc55b00
      accept-language:
      - en-US
  response:
    status:
      code: 202
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      location:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2016-02-01
      retry-after: '1'
      x-ms-ratelimit-remaining-subscription-writes:
      - '1196'
      x-ms-request-id:
      - b75f76b4-def5-421c-a2a5-fe367f774b58
      x-ms-correlation-request-id:
      - b75f76b4-def5-421c-a2a5-fe367f774b58
      x-ms-routing-request-id:
      - WESTUS:20160519T031518Z:b75f76b4-def5-421c-a2a5-fe367f774b58
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:15:18 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 19 May 2016 03:15:20 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 163d3865-e9a6-4fb3-bac0-ee7441a188c9
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-reads:
      - '14970'
      x-ms-request-id:
      - 39b2c305-0256-4bbb-aa70-d74a2e5aa3c2
      x-ms-correlation-request-id:
      - 39b2c305-0256-4bbb-aa70-d74a2e5aa3c2
      x-ms-routing-request-id:
      - WESTUS:20160519T031618Z:39b2c305-0256-4bbb-aa70-d74a2e5aa3c2
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:16:18 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 19 May 2016 03:16:21 GMT
recorded_with: VCR 3.0.1
