---
http_interactions:
- request:
    method: get
    uri: https://login.windows.net/<AZURE_TENANT_ID>/oauth2/token
    body:
      encoding: UTF-8
      string: resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=<AZURE_CLIENT_ID>&client_secret=<AZURE_CLIENT_SECRET>&grant_type=client_credentials
    headers:
      User-Agent:
      - Faraday v0.9.2
      content-type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      server:
      - Microsoft-IIS/8.5
      x-ms-request-id:
      - 399e2d1a-e01d-4e5d-a7d1-82a890ab7ca1
      client-request-id:
      - 5c653aa1-1adb-4abf-809a-5047c6d8e523
      x-ms-gateway-service-instanceid:
      - ESTSFE_IN_185
      x-content-type-options:
      - nosniff
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      p3p:
      - CP="DSP CUR OTPi IND OTRi ONL FIN"
      set-cookie:
      - flight-uxoptin=true; path=/; secure; HttpOnly, esctx=AAABAAAAiL9Kn2Z27UubvWFPbm0gLcXon3AN73px_KmwDehmIxpRILyP2-Z6VPTEKBLhDmlLMSbC98tTaKKNmPStL3pe8YMx3j8flJTJlfjn5tVel10_peBRggrWUc5toEP9cSdJkPhRTXl0gsuD1nk-B5LAoEpQlkupgnUbgQuM6KiyqNqlq5z6mtTlUps_-0kU82XLIAA;
        domain=.login.windows.net; path=/; secure; HttpOnly, x-ms-gateway-slice=productiona;
        path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
      x-powered-by:
      - ASP.NET
      date:
      - Thu, 19 May 2016 03:16:17 GMT
      connection:
      - close
      content-length:
      - '1234'
    body:
      encoding: UTF-8
      string: '{"token_type":"Bearer","expires_in":"3600","expires_on":"1463631379","not_before":"1463627479","resource":"https://management.core.windows.net/","access_token":"<ACCESS_TOKEN>"}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:16:21 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2016-02-01
    body:
      encoding: UTF-8
      string: '{"location":"westus"}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - f7e40a45-e298-44cf-9128-69746df660a5
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-length:
      - '217'
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-writes:
      - '1197'
      x-ms-request-id:
      - fc649415-6b9c-49a9-8978-183a9bb3e530
      x-ms-correlation-request-id:
      - fc649415-6b9c-49a9-8978-183a9bb3e530
      x-ms-routing-request-id:
      - WESTUS:20160519T031620Z:fc649415-6b9c-49a9-8978-183a9bb3e530
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:16:20 GMT
      connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources","name":"RubySDKTest_azure_mgmt_resources","location":"westus","properties":{"provisioningState":"Succeeded"}}'
    http_version: 
  recorded_at: Thu, 19 May 2016 03:16:22 GMT
- request:
    method: delete
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 16fb6b44-6237-4760-b349-d73fdbf22e90
      accept-language:
      - en-US
  response:
    status:
      code: 202
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      location:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2016-02-01
      retry-after: '1'
      x-ms-ratelimit-remaining-subscription-writes:
      - '1195'
      x-ms-request-id:
      - a3fa285f-fe30-4f86-a5d4-1decacb3461d
      x-ms-correlation-request-id:
      - a3fa285f-fe30-4f86-a5d4-1decacb3461d
      x-ms-routing-request-id:
      - WESTUS:20160519T031620Z:a3fa285f-fe30-4f86-a5d4-1decacb3461d
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:16:19 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 19 May 2016 03:16:22 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - aa39c0c6-0291-4f80-98f3-2f43f8ebafd1
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-reads:
      - '14990'
      x-ms-request-id:
      - 4976d112-2a63-41b0-97bb-1b6b50530746
      x-ms-correlation-request-id:
      - 4976d112-2a63-41b0-97bb-1b6b50530746
      x-ms-routing-request-id:
      - WESTUS:20160519T031721Z:4976d112-2a63-41b0-97bb-1b6b50530746
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Thu, 19 May 2016 03:17:21 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 19 May 2016 03:17:23 GMT
recorded_with: VCR 3.0.1
