---
http_interactions:
- request:
    method: get
    uri: https://login.windows.net/<AZURE_TENANT_ID>/oauth2/token
    body:
      encoding: UTF-8
      string: resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=<AZURE_CLIENT_ID>&client_secret=<AZURE_CLIENT_SECRET>&grant_type=client_credentials
    headers:
      User-Agent:
      - Faraday v0.9.2
      content-type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      server:
      - Microsoft-IIS/8.5
      x-ms-request-id:
      - d21eff7c-f0cf-4edf-87c7-7a9c8fb24f1d
      client-request-id:
      - 9581c902-40b6-463b-b35b-8e3a1eb60773
      x-ms-gateway-service-instanceid:
      - ESTSFE_IN_46
      x-content-type-options:
      - nosniff
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      p3p:
      - CP="DSP CUR OTPi IND OTRi ONL FIN"
      set-cookie:
      - flight-uxoptin=true; path=/; secure; HttpOnly, x-ms-gateway-slice=productionb;
        path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
      x-powered-by:
      - ASP.NET
      date:
      - Fri, 22 Apr 2016 18:44:40 GMT
      connection:
      - close
      content-length:
      - '1234'
    body:
      encoding: UTF-8
      string: '{"token_type":"Bearer","expires_in":"3599","expires_on":"1461354281","not_before":"1461350381","resource":"https://management.core.windows.net/","access_token":"<ACCESS_TOKEN>"}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:44:44 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2015-11-01
    body:
      encoding: UTF-8
      string: '{"location":"westus"}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - ff7c3bc8-d17f-4baf-aa32-48a60c2c6a98
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-length:
      - '217'
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-writes:
      - '1199'
      x-ms-request-id:
      - c036bed4-2ce6-414c-ba6d-a3b0def13fb4
      x-ms-correlation-request-id:
      - c036bed4-2ce6-414c-ba6d-a3b0def13fb4
      x-ms-routing-request-id:
      - CENTRALUS:20160422T184442Z:c036bed4-2ce6-414c-ba6d-a3b0def13fb4
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:44:42 GMT
      connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources","name":"RubySDKTest_azure_mgmt_resources","location":"westus","properties":{"provisioningState":"Succeeded"}}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:44:46 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/?api-version=2015-11-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 7f6defd4-3f83-4d6b-afbf-4cc4bbe4893a
      accept-language:
      - en-US
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14998'
      x-ms-request-id:
      - 2297051e-e28a-477c-8dd2-118da404bbf8
      x-ms-correlation-request-id:
      - 2297051e-e28a-477c-8dd2-118da404bbf8
      x-ms-routing-request-id:
      - CENTRALUS:20160422T184443Z:2297051e-e28a-477c-8dd2-118da404bbf8
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:44:42 GMT
      connection:
      - close
      content-length:
      - '133'
    body:
      encoding: ASCII-8BIT
      string: '{"value":[]}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:44:46 GMT
- request:
    method: delete
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2015-11-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 890d34ea-1330-4280-b945-a632d2b4401e
      accept-language:
      - en-US
  response:
    status:
      code: 202
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      location:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2015-11-01
      retry-after: '1'
      x-ms-ratelimit-remaining-subscription-writes:
      - '1198'
      x-ms-request-id:
      - 62f5c875-4609-433e-87db-1b073300a7ea
      x-ms-correlation-request-id:
      - 62f5c875-4609-433e-87db-1b073300a7ea
      x-ms-routing-request-id:
      - CENTRALUS:20160422T184444Z:62f5c875-4609-433e-87db-1b073300a7ea
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:44:43 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:44:47 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2015-11-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - cdc69906-0c2e-4ee6-8bae-c5c1744f6ac7
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-reads:
      - '14998'
      x-ms-request-id:
      - afa9aecd-2a62-4b8e-8426-d493faa40d91
      x-ms-correlation-request-id:
      - afa9aecd-2a62-4b8e-8426-d493faa40d91
      x-ms-routing-request-id:
      - CENTRALUS:20160422T184545Z:afa9aecd-2a62-4b8e-8426-d493faa40d91
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:45:45 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:45:48 GMT
recorded_with: VCR 3.0.1
