---
http_interactions:
- request:
    method: get
    uri: https://login.windows.net/<AZURE_TENANT_ID>/oauth2/token
    body:
      encoding: UTF-8
      string: resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=<AZURE_CLIENT_ID>&client_secret=<AZURE_CLIENT_SECRET>&grant_type=client_credentials
    headers:
      User-Agent:
      - Faraday v0.9.2
      content-type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      server:
      - Microsoft-IIS/8.5
      x-ms-request-id:
      - b183e4b2-e210-4fec-a640-cd24810edd8b
      client-request-id:
      - 2c99a43f-7f9f-4912-9911-7a66e5656546
      x-ms-gateway-service-instanceid:
      - ESTSFE_IN_418
      x-content-type-options:
      - nosniff
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      p3p:
      - CP="DSP CUR OTPi IND OTRi ONL FIN"
      set-cookie:
      - flight-uxoptin=true; path=/; secure; HttpOnly, x-ms-gateway-slice=productionb;
        path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
      x-powered-by:
      - ASP.NET
      date:
      - Fri, 22 Apr 2016 18:38:58 GMT
      connection:
      - close
      content-length:
      - '1234'
    body:
      encoding: UTF-8
      string: '{"token_type":"Bearer","expires_in":"3600","expires_on":"1461353939","not_before":"1461350039","resource":"https://management.core.windows.net/","access_token":"<ACCESS_TOKEN>"}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:39:02 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2015-11-01
    body:
      encoding: UTF-8
      string: '{"location":"westus"}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - afe259e0-0b44-4e97-9e29-228221078130
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-length:
      - '217'
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-writes:
      - '1198'
      x-ms-request-id:
      - 670d87a7-5722-4b3d-8e65-1225810518e3
      x-ms-correlation-request-id:
      - 670d87a7-5722-4b3d-8e65-1225810518e3
      x-ms-routing-request-id:
      - WESTUS:20160422T183859Z:670d87a7-5722-4b3d-8e65-1225810518e3
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:38:59 GMT
      connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources","name":"RubySDKTest_azure_mgmt_resources","location":"westus","properties":{"provisioningState":"Succeeded"}}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:39:03 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test?api-version=2015-11-01
    body:
      encoding: UTF-8
      string: '{"properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json"},"parameters":{"databaseAccountName":{"value":"mydocs-test"}},"mode":"Incremental"}}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - d3785e55-82cf-48d8-ba27-08173ee31443
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      azure-asyncoperation:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test/operationStatuses/08587402565448574886?api-version=2015-11-01
      x-ms-ratelimit-remaining-subscription-writes:
      - '1198'
      x-ms-request-id:
      - 2635d07f-6aa5-4ca3-914e-7a3b3ad3fe2b
      x-ms-correlation-request-id:
      - 2635d07f-6aa5-4ca3-914e-7a3b3ad3fe2b
      x-ms-routing-request-id:
      - WESTUS:20160422T183900Z:2635d07f-6aa5-4ca3-914e-7a3b3ad3fe2b
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:39:00 GMT
      connection:
      - close
      content-length:
      - '778'
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test","name":"Deployment_test","properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json","contentVersion":"1.0.0.0"},"parameters":{"databaseAccountName":{"type":"String","value":"mydocs-test"}},"mode":"Incremental","provisioningState":"Accepted","timestamp":"2016-04-22T18:39:00.7436584Z","duration":"PT0.1234849S","correlationId":"2635d07f-6aa5-4ca3-914e-7a3b3ad3fe2b","providers":[{"namespace":"Microsoft.DocumentDB","resourceTypes":[{"resourceType":"databaseAccounts","locations":["westus"]}]}],"dependencies":[]}}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:39:04 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test/operationStatuses/08587402565448574886?api-version=2015-11-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 0c98bedb-57c1-473f-83e5-cbd8427fee53
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14996'
      x-ms-request-id:
      - 75819c34-37b9-48fd-b589-5b31dab8764c
      x-ms-correlation-request-id:
      - 75819c34-37b9-48fd-b589-5b31dab8764c
      x-ms-routing-request-id:
      - WESTUS:20160422T183931Z:75819c34-37b9-48fd-b589-5b31dab8764c
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:39:30 GMT
      connection:
      - close
      content-length:
      - '140'
    body:
      encoding: ASCII-8BIT
      string: '{"status":"Running"}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:39:34 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test/operationStatuses/08587402565448574886?api-version=2015-11-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 6d8fc640-38a1-488e-af37-c97291440371
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14994'
      x-ms-request-id:
      - 4e2ddb4c-72ab-4250-b8e3-235c4c0c7996
      x-ms-correlation-request-id:
      - 4e2ddb4c-72ab-4250-b8e3-235c4c0c7996
      x-ms-routing-request-id:
      - WESTUS:20160422T184002Z:4e2ddb4c-72ab-4250-b8e3-235c4c0c7996
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:40:02 GMT
      connection:
      - close
      content-length:
      - '141'
    body:
      encoding: ASCII-8BIT
      string: '{"status":"Succeeded"}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:40:06 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test?api-version=2015-11-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 7bd85c79-7a04-4644-99c8-9debdd1815d0
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14995'
      x-ms-request-id:
      - b0ad5430-0fa1-421d-a2ce-7dfce7862793
      x-ms-correlation-request-id:
      - b0ad5430-0fa1-421d-a2ce-7dfce7862793
      x-ms-routing-request-id:
      - WESTUS:20160422T184002Z:b0ad5430-0fa1-421d-a2ce-7dfce7862793
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:40:02 GMT
      connection:
      - close
      content-length:
      - '683'
    body:
      encoding: ASCII-8BIT
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test","name":"Deployment_test","properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json","contentVersion":"1.0.0.0"},"parameters":{"databaseAccountName":{"type":"String","value":"mydocs-test"}},"mode":"Incremental","provisioningState":"Succeeded","timestamp":"2016-04-22T18:39:47.3390039Z","duration":"PT46.7188304S","correlationId":"2635d07f-6aa5-4ca3-914e-7a3b3ad3fe2b","providers":[{"namespace":"Microsoft.DocumentDB","resourceTypes":[{"resourceType":"databaseAccounts","locations":["westus"]}]}],"dependencies":[],"outputResources":[{"id":"Microsoft.DocumentDB/databaseAccounts/mydocs-test"}]}}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:40:06 GMT
- request:
    method: post
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test/validate?api-version=2015-11-01
    body:
      encoding: UTF-8
      string: '{"properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json"},"parameters":{"databaseAccountName":{"value":"mydocs-test"}},"mode":"Incremental"}}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - f546bbe8-528e-45a9-9803-eeb68bb25d8b
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-writes:
      - '1196'
      x-ms-request-id:
      - 997e0435-65d7-4e33-a145-387c056f7cd0
      x-ms-correlation-request-id:
      - 997e0435-65d7-4e33-a145-387c056f7cd0
      x-ms-routing-request-id:
      - WESTUS:20160422T184003Z:997e0435-65d7-4e33-a145-387c056f7cd0
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:40:03 GMT
      connection:
      - close
      content-length:
      - '733'
    body:
      encoding: ASCII-8BIT
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test","name":"Deployment_test","properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json","contentVersion":"1.0.0.0"},"parameters":{"databaseAccountName":{"type":"String","value":"mydocs-test"}},"mode":"Incremental","provisioningState":"Accepted","timestamp":"2016-04-22T18:40:03.8175753Z","duration":"PT0S","correlationId":"997e0435-65d7-4e33-a145-387c056f7cd0","providers":[{"namespace":"Microsoft.DocumentDB","resourceTypes":[{"resourceType":"databaseAccounts","locations":["westus"]}]}],"dependencies":[],"validatedResources":[{"apiVersion":"2015-04-08","id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.DocumentDB/databaseAccounts/mydocs-test","name":"mydocs-test","type":"Microsoft.DocumentDB/databaseAccounts","location":"westus","properties":{"name":"mydocs-test","databaseAccountOfferType":"Standard"}}]}}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:40:07 GMT
- request:
    method: post
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test/validate?api-version=2015-11-01
    body:
      encoding: UTF-8
      string: '{"properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json"},"parameters":{"databaseAccountName":{"value":"mydocs-test"}},"mode":"Incremental"}}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 52497579-287d-4f22-90bd-ff0a8efdb178
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-writes:
      - '1197'
      x-ms-request-id:
      - 83de9c11-ac20-4f58-ba54-f364745144ac
      x-ms-correlation-request-id:
      - 83de9c11-ac20-4f58-ba54-f364745144ac
      x-ms-routing-request-id:
      - WESTUS:20160422T184004Z:83de9c11-ac20-4f58-ba54-f364745144ac
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:40:04 GMT
      connection:
      - close
      content-length:
      - '730'
    body:
      encoding: ASCII-8BIT
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.Resources/deployments/Deployment_test","name":"Deployment_test","properties":{"templateLink":{"uri":"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-documentdb-account-create/azuredeploy.json","contentVersion":"1.0.0.0"},"parameters":{"databaseAccountName":{"type":"String","value":"mydocs-test"}},"mode":"Incremental","provisioningState":"Accepted","timestamp":"2016-04-22T18:40:04.5439416Z","duration":"PT0S","correlationId":"83de9c11-ac20-4f58-ba54-f364745144ac","providers":[{"namespace":"Microsoft.DocumentDB","resourceTypes":[{"resourceType":"databaseAccounts","locations":["westus"]}]}],"dependencies":[],"validatedResources":[{"apiVersion":"2015-04-08","id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources/providers/Microsoft.DocumentDB/databaseAccounts/mydocs-test","name":"mydocs-test","type":"Microsoft.DocumentDB/databaseAccounts","location":"westus","properties":{"name":"mydocs-test","databaseAccountOfferType":"Standard"}}]}}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:40:07 GMT
- request:
    method: delete
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2015-11-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - e8a7c172-7aa2-4c10-8efa-f249a710930c
      accept-language:
      - en-US
  response:
    status:
      code: 202
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      location:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2015-11-01
      retry-after: '1'
      x-ms-ratelimit-remaining-subscription-writes:
      - '1198'
      x-ms-request-id:
      - 73ff003b-b0fd-4e70-bc39-e03c08f9dd34
      x-ms-correlation-request-id:
      - 73ff003b-b0fd-4e70-bc39-e03c08f9dd34
      x-ms-routing-request-id:
      - WESTUS:20160422T184005Z:73ff003b-b0fd-4e70-bc39-e03c08f9dd34
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:40:04 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:40:08 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2015-11-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 7a18035d-6e4e-4bb4-95d4-899c1ca37ea8
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-reads:
      - '14996'
      x-ms-request-id:
      - 47d87e8b-23d3-419d-880f-44518e42cc74
      x-ms-correlation-request-id:
      - 47d87e8b-23d3-419d-880f-44518e42cc74
      x-ms-routing-request-id:
      - WESTUS:20160422T184337Z:47d87e8b-23d3-419d-880f-44518e42cc74
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:43:37 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:43:41 GMT
recorded_with: VCR 3.0.1
