---
http_interactions:
- request:
    method: get
    uri: https://login.windows.net/<AZURE_TENANT_ID>/oauth2/token
    body:
      encoding: UTF-8
      string: resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=<AZURE_CLIENT_ID>&client_secret=<AZURE_CLIENT_SECRET>&grant_type=client_credentials
    headers:
      User-Agent:
      - Faraday v0.9.2
      content-type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      server:
      - Microsoft-IIS/8.5
      x-ms-request-id:
      - 8210de44-2831-4f17-bf48-cafa24f3de68
      client-request-id:
      - b0e9986b-d1ce-468d-83aa-56d1740763b6
      x-ms-gateway-service-instanceid:
      - ESTSFE_IN_517
      x-content-type-options:
      - nosniff
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      p3p:
      - CP="DSP CUR OTPi IND OTRi ONL FIN"
      set-cookie:
      - flight-uxoptin=true; path=/; secure; HttpOnly, x-ms-gateway-slice=productionb;
        path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
      x-powered-by:
      - ASP.NET
      date:
      - Fri, 22 Apr 2016 18:33:45 GMT
      connection:
      - close
      content-length:
      - '1234'
    body:
      encoding: UTF-8
      string: '{"token_type":"Bearer","expires_in":"3599","expires_on":"1461353627","not_before":"1461349727","resource":"https://management.core.windows.net/","access_token":"<ACCESS_TOKEN>"}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:33:50 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2015-11-01
    body:
      encoding: UTF-8
      string: '{"location":"westus"}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 18602f28-f84e-4154-8079-77bb2ceba02b
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-length:
      - '217'
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-writes:
      - '1199'
      x-ms-request-id:
      - 6e244edc-8df2-47d6-a07e-ddf53498d9b4
      x-ms-correlation-request-id:
      - 6e244edc-8df2-47d6-a07e-ddf53498d9b4
      x-ms-routing-request-id:
      - WESTUS:20160422T183347Z:6e244edc-8df2-47d6-a07e-ddf53498d9b4
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:33:46 GMT
      connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/RubySDKTest_azure_mgmt_resources","name":"RubySDKTest_azure_mgmt_resources","location":"westus","properties":{"provisioningState":"Succeeded"}}'
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:33:51 GMT
- request:
    method: delete
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/RubySDKTest_azure_mgmt_resources?api-version=2015-11-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - d9b4ee01-bc52-42c6-8cc8-1effd5f1ca0b
      accept-language:
      - en-US
  response:
    status:
      code: 202
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      location:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2015-11-01
      retry-after: '1'
      x-ms-ratelimit-remaining-subscription-writes:
      - '1197'
      x-ms-request-id:
      - b110dd93-0fac-4baf-917b-057e6774fc8f
      x-ms-correlation-request-id:
      - b110dd93-0fac-4baf-917b-057e6774fc8f
      x-ms-routing-request-id:
      - WESTUS:20160422T183348Z:b110dd93-0fac-4baf-917b-057e6774fc8f
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:33:47 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:33:51 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SVUJZU0RLVEVTVDo1RkFaVVJFOjVGTUdNVDo1RlJFU09VUkNFUy1XRVNUVVMiLCJqb2JMb2NhdGlvbiI6Indlc3R1cyJ9?api-version=2015-11-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.2.1/
      x-ms-client-request-id:
      - 49b3de96-16b9-4cf1-aaeb-48637915dfd6
      accept-language:
      - en-US
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-reads:
      - '14996'
      x-ms-request-id:
      - d6720283-f87e-43dd-9b28-7b69f6e1376b
      x-ms-correlation-request-id:
      - d6720283-f87e-43dd-9b28-7b69f6e1376b
      x-ms-routing-request-id:
      - WESTUS:20160422T183448Z:d6720283-f87e-43dd-9b28-7b69f6e1376b
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Fri, 22 Apr 2016 18:34:48 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 22 Apr 2016 18:34:52 GMT
recorded_with: VCR 3.0.1
