# Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
# Changes may cause incorrect behavior and will be lost if the code is


module Azure::ARM::Storage
  #
  # Defines values for Reason
  #
  module Reason
    AccountNameInvalid = "AccountNameInvalid"
    AlreadyExists = "AlreadyExists"
  end
end
