# Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
# Changes may cause incorrect behavior and will be lost if the code is


module Azure::ARM::Storage
  module Models
    #
    # Model object.
    #
    class StorageAccountRegenerateKeyParameters
      # @return Possible values for this property include: 'key1', 'key2'
      attr_accessor :key_name

      #
      # Validate the object. Throws ArgumentError if validation fails.
      #
      def validate
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(object)
        object.validate
        output_object = {}

        serialized_property = object.key_name
        output_object['keyName'] = serialized_property unless serialized_property.nil?

        output_object
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [StorageAccountRegenerateKeyParameters] Deserialized object.
      #
      def self.deserialize_object(object)
        return if object.nil?
        output_object = StorageAccountRegenerateKeyParameters.new

        deserialized_property = object['keyName']
        fail MsRest::DeserializationError.new('Error occured in deserializing the enum', nil, nil, nil) if (!deserialized_property.nil? && !deserialized_property.empty? && !Azure::ARM::Storage::KeyName.constants.any? { |e| Azure::ARM::Storage::KeyName.const_get(e) == deserialized_property })
        output_object.key_name = deserialized_property

        output_object.validate

        output_object
      end
    end
  end
end
