# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

source 'https://rubygems.org'

gemspec

group :development, :local, :test do
  gem 'rspec'
  gem 'json'
  gem 'concurrent-ruby-ext'
  gem 'faraday'
  gem 'faraday-cookie_jar'
  gem 'ms_rest_azure'
  gem 'azure_resource_management'
  gem 'azure_storage_management'
  gem 'azure_network_management'
end